# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAcG8idtykd7JMrIbVVS7jyVrsI4IUvb
"""

# -----------------------------
# 0. Import Libraries
# -----------------------------
import zipfile
import os
import random
import pandas as pd
import numpy as np
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, f1_score, mean_squared_error,
    confusion_matrix, roc_auc_score
)

from imblearn.combine import SMOTEENN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# -----------------------------
# 1. Reproducibility settings
# -----------------------------
seed = 42
random.seed(seed)
np.random.seed(seed)
tf.random.set_seed(seed)
os.environ['TF_DETERMINISTIC_OPS'] = '1'
os.environ['TF_CUDNN_DETERMINISM'] = '1'

# -----------------------------
# 2. Unzip and Load Data
# -----------------------------
zip_path = '/content/blood+transfusion+service+center.zip'
extracted_path = 'extracted_dataset'

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extracted_path)
print(f"✅ Dataset extracted to {extracted_path}")

df = pd.read_csv(
    os.path.join(extracted_path, 'transfusion.data'),
    names=['Recency', 'Frequency', 'Monetary', 'Time', 'Donated']
)

# -----------------------------
# 3. Preprocessing
# -----------------------------
df = df.apply(pd.to_numeric, errors='coerce')
df.fillna(df.median(), inplace=True)

# Feature Engineering
df['Recency_Time_Ratio'] = df['Recency'] / (df['Time'] + 1)
df['Frequency_Monetary'] = df['Frequency'] * df['Monetary']

# Separate features and target
X = df[['Recency', 'Frequency', 'Monetary', 'Time',
        'Recency_Time_Ratio', 'Frequency_Monetary']]
y = df['Donated']

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=seed, stratify=y
)

# Standard Scaling
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

# -----------------------------
# 4. Balance the Data
# -----------------------------
sme = SMOTEENN(random_state=seed)
X_res, y_res = sme.fit_resample(X_train_s, y_train)
print("✅ After SMOTE+ENN, training size:", X_res.shape)

# -----------------------------
# 5. Build the Model (correct way)
# -----------------------------
model = Sequential([
    Input(shape=(X_res.shape[1],)),    # ✅ Proper input layer
    Dense(512, activation='relu'),
    BatchNormalization(),
    Dropout(0.4, seed=seed),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.3, seed=seed),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

opt = tf.keras.optimizers.Nadam(learning_rate=1e-3)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

# -----------------------------
# 6. Train the Model
# -----------------------------
es = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)
rlr = ReduceLROnPlateau(monitor='val_loss', patience=10, factor=0.5, verbose=1)

history = model.fit(
    X_res, y_res,
    validation_data=(X_test_s, y_test),
    epochs=200,
    batch_size=16,
    callbacks=[es, rlr],
    verbose=1
)

# -----------------------------
# 7. Predict & Evaluate
# -----------------------------
y_prob = model.predict(X_test_s).ravel()

# Find best threshold
best_thresh = 0.5
best_balance = 0.0

for t in np.linspace(0.1, 0.9, 81):
    y_pred_t = (y_prob > t).astype(int)
    acc_t = accuracy_score(y_test, y_pred_t)
    f1_t  = f1_score(y_test, y_pred_t)
    balance = (acc_t + f1_t) / 2.0
    if balance > best_balance:
        best_balance = balance
        best_thresh = t

# Final Evaluation
y_pred_best = (y_prob > best_thresh).astype(int)
acc_best = accuracy_score(y_test, y_pred_best)
f1_best = f1_score(y_test, y_pred_best)
rmse_best = np.sqrt(mean_squared_error(y_test, y_pred_best))
auc_score = roc_auc_score(y_test, y_prob)

print(f"\n🔍 Best Threshold: {best_thresh:.2f}")
print(f"Accuracy: {acc_best*100:.2f}%")
print(f"F1 Score: {f1_best:.4f}")
print(f"RMSE: {rmse_best:.4f}")
print(f"AUC-ROC: {auc_score:.4f}")
print(f"Balanced metric (Accuracy+F1 avg): {best_balance:.4f}")

# -----------------------------
# 8. Confusion Matrix
# -----------------------------
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title(f'Confusion Matrix (thr={best_thresh:.2f})')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# -----------------------------

# -----------------------------
model.save('/content/final_tuned_balanced_mlp_model.keras')

pip install --upgrade mlflow

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import mlflow
print(mlflow.__version__)

import mlflow
import mlflow.tensorflow
import tensorflow as tf
import numpy as np

# Load your trained model in the correct format (SavedModel format)
model = tf.keras.models.load_model('/content/final_tuned_balanced_mlp_model.keras')

# Define metrics and parameters
optimizer = "Nadam"
learning_rate = 1e-3
batch_size = 16
epochs_trained = 50
SMOTEENN_applied = True
acc_best = 0.85
f1_best = 0.80
rmse_best = 0.1
auc = 0.88
best_thresh = 0.5

# Prepare an input example (6 features)
input_example = np.random.rand(1, 6).astype(np.float32)

# Start MLflow run
with mlflow.start_run(run_name="Blood Transfusion MLP Model (fixed)"):

    # Log parameters
    mlflow.log_params({
        "optimizer": optimizer,
        "learning_rate": learning_rate,
        "batch_size": batch_size,
        "epochs_trained": epochs_trained,
        "SMOTEENN_applied": SMOTEENN_applied
    })

    # Log metrics
    mlflow.log_metrics({
        "best_accuracy": acc_best,
        "best_f1_score": f1_best,
        "rmse": rmse_best,
        "auc_roc": auc,
        "best_threshold": best_thresh
    })

    # ✅ Log model properly using TensorFlow flavor
    mlflow.tensorflow.log_model(
        model,  # Directly log the model object
        artifact_path="model",
        input_example=input_example
    )

    print("✅ Model and metrics logged to MLflow successfully without any error.")

import os

# Define the path to the mlruns directory
mlruns_dir = '/content/mlruns'

# Check if the mlruns directory exists
if os.path.exists(mlruns_dir):
    # Check if there are any directories inside mlruns
    run_dirs = os.listdir(mlruns_dir)

    if run_dirs:
        print("Contents of mlruns/ directory:")
        for run in run_dirs:
            print(f"- {run}")
    else:
        print("The mlruns directory exists, but it doesn't contain any saved runs.")
else:
    print("mlruns/ directory does not exist. Please ensure MLflow has logged some runs.")

# List contents of the '0' experiment folder
experiment_dir = os.path.join(mlruns_dir, '0')

if os.path.exists(experiment_dir):
    print("Contents of '0' experiment directory:")
    print(os.listdir(experiment_dir))
else:
    print("Experiment directory '0' not found.")

mlruns_dir = "/content/mlruns"

import os

experiment_dir = os.path.join(mlruns_dir, '0')
print("Available runs:", os.listdir(experiment_dir))

import os

experiment_dir = os.path.join("/content/mlruns", '0')
print("Available run directories:", os.listdir(experiment_dir))

run_id = "daab4ca0d0d74ba99eab0cbb745579db"
run_dir = os.path.join(experiment_dir, run_id)
print("Contents of run directory:", os.listdir(run_dir))

params_dir = os.path.join(run_dir, 'params')
print("Contents of params directory:", os.listdir(params_dir))

import os

# Define the params directory
params_dir = os.path.join(mlruns_dir, '0', 'daab4ca0d0d74ba99eab0cbb745579db', 'params')

# Initialize an empty dictionary to store the parameters
params = {}

# Loop through each file in the params directory and read the values
for param_file in os.listdir(params_dir):
    param_path = os.path.join(params_dir, param_file)
    with open(param_path, 'r') as f:
        params[param_file] = f.read().strip()

# Print the extracted parameters
print("Extracted parameters:")
for param_name, param_value in params.items():
    print(f"{param_name}: {param_value}")

# Check the contents of a specific run directory
run_id = 'daab4ca0d0d74ba99eab0cbb745579db'
run_path = os.path.join(experiment_dir, run_id)

if os.path.exists(run_path):
    print(f"Contents of run directory {run_id}:")
    print(os.listdir(run_path))
else:
    print(f"Run directory {run_id} not found.")

import matplotlib.pyplot as plt

# Plot training & validation accuracy
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Plot training & validation loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training vs Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

import mlflow.pyfunc
import numpy as np

# Load the model for inference
model_uri = 'runs:/daab4ca0d0d74ba99eab0cbb745579db/model'  # Correct run ID
loaded_model = mlflow.pyfunc.load_model(model_uri)

# Use a consistent shape and avoid randomness
input_example = np.array([[0.1, 2.0, 200.0, 4.0, 0.025, 400.0]], dtype=np.float32)
predictions = loaded_model.predict(input_example)

print(f"Predictions: {predictions}")

import os

# Define the path to the mlruns directory and the experiment ID
mlruns_dir = '/content/mlruns'
experiment_id = '0'  # experiment ID
run_id = 'daab4ca0d0d74ba99eab0cbb745579db'  # example run ID

# Build the full path to the experiment directory
experiment_dir = os.path.join(mlruns_dir, experiment_id)
run_path = os.path.join(experiment_dir, run_id)

# Check if run_path exists and is a directory
if os.path.isdir(run_path):
    print(f"Run ID: {run_id}")
    print(f"Contents: {os.listdir(run_path)}")
else:
    print(f"{run_path} is not a valid directory.")

!pip install -q streamlit pyngrok mlflow scikit-learn imbalanced-learn

!pip install streamlit pyngrok mlflow --quiet

from pyngrok import conf, ngrok

conf.get_default().auth_token = "2wLF2flmJW4Oh6ShJZuxRcNqK6d_89KvNqx2BooSCv8Az5GYs"

app_code = """
import streamlit as st
import mlflow.pyfunc
import numpy as np

st.title("🩸 Blood Donation Prediction App")

run_id = "daab4ca0d0d74ba99eab0cbb745579db"
model_uri = f"runs:/{run_id}/model"
model = mlflow.pyfunc.load_model(model_uri)

st.markdown("Enter your details:")

features = [
    st.number_input("Recency", min_value=0.0),
    st.number_input("Frequency", min_value=0.0),
    st.number_input("Monetary", min_value=0.0),
    st.number_input("Time", min_value=0.0),
    st.number_input("Recency / Time Ratio", min_value=0.0),
    st.number_input("Frequency × Monetary", min_value=0.0)
]

if st.button("Predict"):
    input_array = np.array(features).reshape(1, -1).astype(np.float32)
    prediction = model.predict(input_array)
    score = prediction.item()
    st.success(f"🧪 Predicted Donation Likelihood: {score:.4f}")
"""

with open("app.py", "w") as f:
    f.write(app_code)
print("✅ Streamlit app code written successfully.")

# 1. Ensure a clean ngrok setup
!pkill -f ngrok > /dev/null 2>&1  # Kill ngrok processes (if any)
!pkill -f streamlit > /dev/null 2>&1  # Kill Streamlit (if any)

# 2. (One-time) Set ngrok auth token — paste your actual token below
!ngrok config add-authtoken 2wLF2flmJW4Oh6ShJZuxRcNqK6d_89KvNqx2BooSCv8Az5GYs

# 3. Start Streamlit app in background
!streamlit run app.py &> /content/log.txt &

# 4. Wait a few seconds for Streamlit to start
import time
time.sleep(5)

# 5. Start ngrok tunnel and display the public URL
from pyngrok import ngrok
ngrok.kill()  # Clean up tunnels (important before connect)
public_url = ngrok.connect(8501)
print(f"🌐 Your Streamlit app is live: {public_url}")